# docker-compose.yml
version: '3.8'
services:
  redis:
    image: redis
    container_name: queue
    expose:
      - 6379
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/opt/app
    ports:
      - 3001:3001
    environment:
      - REDIS_URL=redis://queue
      - NODE_ENV=production
      - PORT=3001
    command: npm start